language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo build --release --verbose
  - cargo test --verbose
  - cargo clippy -- -D warnings --verbose
  - cargo fmt -- --check --verbose
cache: cargo
